<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Config.Net" Version="4.15.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="MaterialDesign.Icons" Version="1.1.0" />
    <PackageReference Include="MaterialDesignThemes" Version="3.2.0" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\PluginSystem\PluginSystem.Abstractions\PluginSystem.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\UnityCommander.Abstractions\UnityCommander.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\UnityCommander.Common\UnityCommander.Common.csproj" />
    <ProjectReference Include="..\..\..\UnityCommander.Logging\UnityCommander.Logging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="UnityCommander.Ribbon.Abstractions">
      <HintPath>..\..\..\..\..\_builds\UnityCommander.Ribbon.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="UnityCommander.Ribbon.Core">
      <HintPath>..\..\..\..\..\_builds\UnityCommander.Ribbon.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Command\" />
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y /d &quot;$(TargetPath)&quot; &quot;$(SolutionDir)..\_builds\&quot;" />
	</Target>
</Project>