<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Brushes\**" />
    <EmbeddedResource Remove="Brushes\**" />
    <None Remove="Brushes\**" />
    <Page Remove="Brushes\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnityCommander.Abstractions\UnityCommander.Abstractions.csproj" />
    <ProjectReference Include="..\UnityCommander.Diagnostics\UnityCommander.Diagnostics.csproj" />
    <ProjectReference Include="..\UnityCommander.Theme\UnityCommander.Theme.csproj" />
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y /d &quot;$(TargetPath)&quot; &quot;$(SolutionDir)..\_builds\&quot;" />
	</Target>
</Project>
