<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityCommander.Ribbon.Abstractions">
      <HintPath>..\..\..\_builds\UnityCommander.Ribbon.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="UnityCommander.Ribbon.Core">
      <HintPath>..\..\..\_builds\UnityCommander.Ribbon.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
    <Folder Include="Settings\" />
  </ItemGroup>

</Project>
