<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\UnityCommander.Services.Interfaces\UnityCommander.Services.Interfaces\UnityCommander.Services.Interfaces.csproj" />
    <ProjectReference Include="..\UnityCommander.Common\UnityCommander.Common.csproj" />
    <ProjectReference Include="..\UnityCommander.Core\UnityCommander.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Popup\" />
  </ItemGroup>

</Project>
